// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbH_TM5bDcbwFtSeLJ05WzC3rnVuJPhJo',
    appId: '1:757110751567:web:fa0218246c9eb32733c53a',
    messagingSenderId: '757110751567',
    projectId: 'authtutorial-f52cd',
    authDomain: 'authtutorial-f52cd.firebaseapp.com',
    storageBucket: 'authtutorial-f52cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdGIb5YT8SPZmzJuaZEIhQ0piayr5Q_lc',
    appId: '1:757110751567:android:fefaceaf7e55011433c53a',
    messagingSenderId: '757110751567',
    projectId: 'authtutorial-f52cd',
    storageBucket: 'authtutorial-f52cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh9_Z9JydkE7Lmuuk7LGXs_YmiR8SgXXM',
    appId: '1:757110751567:ios:c2551e45b1a598ac33c53a',
    messagingSenderId: '757110751567',
    projectId: 'authtutorial-f52cd',
    storageBucket: 'authtutorial-f52cd.appspot.com',
    iosClientId: '757110751567-4ji21lmvj3apbd5k7lvgp9cu1gt51rua.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh9_Z9JydkE7Lmuuk7LGXs_YmiR8SgXXM',
    appId: '1:757110751567:ios:c2551e45b1a598ac33c53a',
    messagingSenderId: '757110751567',
    projectId: 'authtutorial-f52cd',
    storageBucket: 'authtutorial-f52cd.appspot.com',
    iosClientId: '757110751567-4ji21lmvj3apbd5k7lvgp9cu1gt51rua.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );
}
